### ISSUE TITLE
«Cannot add or update a child row: a foreign key constraint fails (magento2.sales_order_status_history, CONSTRAINT SALES_ORDER_STATUS_HISTORY_PARENT_ID_SALES_ORDER_ENTITY_ID FOREIGN KEY (parent_id) REFERENCES sales_order (entity_id) ON DELETE CASC), query was: INSERT INTO sales_order_status_history (is_customer_notified, is_visible_on_front, comment, status, entity_name)»

### ISSUE THREAD

**Issue by PoiCheong** [mage2pro/ipay88#20] opened 2020-10-23 03:01 UTC
"0":"SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: 
a foreign key constraint fails 
(`magento2`.`sales_order_status_history`, CONSTRAINT `SALES_ORDER_STATUS_HISTORY_PARENT_ID_SALES_ORDER_ENTITY_ID` FOREIGN KEY (`parent_id`) REFERENCES `sales_order` (`entity_id`) ON DELETE CASC), query was: INSERT INTO `sales_order_status_history` (`is_customer_notified`, `is_visible_on_front`, `comment`, `status`, `entity_name`) VALUES (?, ?, ?, ?, ?)","1":"#1

**Comment by dmitrii-fediuk** [comment] 2020-10-23 09:40
A duplicate of https://github.com/mage2pro/ipay88/issues/18

**Closed as completed by dmitrii-fediuk** 2020-10-23 09:40 UTC
